name: "Update action"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run update script
        run: $GITHUB_WORKSPACE/update.sh
